### ISSUE TITLE
assert_is_instance(im.colorbar[0], Colorbar)   AttributeError: Colorbar instance has no attribute '__getitem__

### ISSUE THREAD

**Issue by yarikoptic** [PyMVPA/PyMVPA#175]
Fails in daily tests and on my laptop

```
  ======================================================================
  ERROR: mvpa2.tests.test_viz.test_imshow
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
      self.test(*self.arg)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20140209_170101/PyMVPA/mvpa2/tests/test_viz.py", line 44, in test_imshow
      assert_is_instance(im.colorbar[0], Colorbar)
  AttributeError: Colorbar instance has no attribute '__getitem__'

```

was introduced in 78d036f9e1bb6a49c9b741a0ebef438328e4630d
