### ISSUE TITLE
AttributeError while importing with latest scipy (0.18.0)

### ISSUE THREAD

**Issue by feilong** [PyMVPA/PyMVPA#500]
I got this importing error after upgrading my scipy to 0.18.0:

```
$ pip install --user 'scipy>=0.18.0'
Collecting scipy>=0.18.0
  Using cached scipy-0.18.0-cp27-cp27m-manylinux1_x86_64.whl
Installing collected packages: scipy
  Found existing installation: scipy 0.17.1
    Uninstalling scipy-0.17.1:
      Successfully uninstalled scipy-0.17.1
Successfully installed scipy-0.18.0
$ python -c "from mvpa2.measures.searchlight import Searchlight"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$HOME/.local/lib/python2.7/site-packages/mvpa2/measures/searchlight.py", line 33, in <module>
    from mvpa2.measures.base import Measure
  File "$HOME/.local/lib/python2.7/site-packages/mvpa2/measures/base.py", line 35, in <module>
    from mvpa2.clfs.stats import auto_null_dist
  File "$HOME/.local/lib/python2.7/site-packages/mvpa2/clfs/stats.py", line 636, in <module>
    from mvpa2.support.scipy.stats import scipy
  File "$HOME/.local/lib/python2.7/site-packages/mvpa2/support/scipy/stats.py", line 62, in <module>
    if rdist.veccdf.nin == 1:
AttributeError: 'rdist_gen' object has no attribute 'veccdf'
```

The problem doesn't exist for earlier versions of scipy:

```
$ pip install --user 'scipy>=0.17.0,<0.18.0'                                                                                                                                                            
Collecting scipy<0.18.0,>=0.17.0
  Using cached scipy-0.17.1-cp27-cp27m-manylinux1_x86_64.whl
Installing collected packages: scipy
Successfully installed scipy-0.17.1
$ python -c "from mvpa2.measures.searchlight import Searchlight"
```

I'm using the latest PyMVPA from pip (2.5.0).

**Comment by andrebeu** [comment]
I am also having this issue when I try to import mvpa2.suite

**Comment by yarikoptic** [comment]
it was fixed in upstream/2.5.0-31-g8ed20bc  (i.e. in 2.6.0 release).
Apparently I have forgotten to upload it to pypi (did for debian/neurodebian though) -- uploaded now (and upload for yakkety is ongoing), give it a shot

**Comment by Namrata96** [comment]
Hi, I'm still facing this issue with 2.4.1 version of pymvpa2. Can you please look into this?

**Comment by yarikoptic** [comment]
the latest one is 2.6.4 . you might want to enable http://neuro.debian.net repository if you would like to get more recent version on your debian/ubuntu
